// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// CompleteReceptionOKCode is the HTTP code returned for type CompleteReceptionOK
const CompleteReceptionOKCode int = 200

/*CompleteReceptionOK Success

swagger:response completeReceptionOK
*/
type CompleteReceptionOK struct {
}

// NewCompleteReceptionOK creates CompleteReceptionOK with default headers values
func NewCompleteReceptionOK() *CompleteReceptionOK {

	return &CompleteReceptionOK{}
}

// WriteResponse to the client
func (o *CompleteReceptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*CompleteReceptionDefault Generic error

swagger:response completeReceptionDefault
*/
type CompleteReceptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCompleteReceptionDefault creates CompleteReceptionDefault with default headers values
func NewCompleteReceptionDefault(code int) *CompleteReceptionDefault {
	if code <= 0 {
		code = 500
	}

	return &CompleteReceptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the complete reception default response
func (o *CompleteReceptionDefault) WithStatusCode(code int) *CompleteReceptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the complete reception default response
func (o *CompleteReceptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the complete reception default response
func (o *CompleteReceptionDefault) WithPayload(payload *models.Error) *CompleteReceptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the complete reception default response
func (o *CompleteReceptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CompleteReceptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
