// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetNextMatchOKCode is the HTTP code returned for type GetNextMatchOK
const GetNextMatchOKCode int = 200

/*GetNextMatchOK Success

swagger:response getNextMatchOK
*/
type GetNextMatchOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetNextMatchResponse `json:"body,omitempty"`
}

// NewGetNextMatchOK creates GetNextMatchOK with default headers values
func NewGetNextMatchOK() *GetNextMatchOK {

	return &GetNextMatchOK{}
}

// WithPayload adds the payload to the get next match o k response
func (o *GetNextMatchOK) WithPayload(payload *models.GetNextMatchResponse) *GetNextMatchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next match o k response
func (o *GetNextMatchOK) SetPayload(payload *models.GetNextMatchResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextMatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetNextMatchDefault Generic error

swagger:response getNextMatchDefault
*/
type GetNextMatchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNextMatchDefault creates GetNextMatchDefault with default headers values
func NewGetNextMatchDefault(code int) *GetNextMatchDefault {
	if code <= 0 {
		code = 500
	}

	return &GetNextMatchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get next match default response
func (o *GetNextMatchDefault) WithStatusCode(code int) *GetNextMatchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get next match default response
func (o *GetNextMatchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get next match default response
func (o *GetNextMatchDefault) WithPayload(payload *models.Error) *GetNextMatchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next match default response
func (o *GetNextMatchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextMatchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
