// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetTeamDetailOKCode is the HTTP code returned for type GetTeamDetailOK
const GetTeamDetailOKCode int = 200

/*GetTeamDetailOK Success

swagger:response getTeamDetailOK
*/
type GetTeamDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewGetTeamDetailOK creates GetTeamDetailOK with default headers values
func NewGetTeamDetailOK() *GetTeamDetailOK {

	return &GetTeamDetailOK{}
}

// WithPayload adds the payload to the get team detail o k response
func (o *GetTeamDetailOK) WithPayload(payload *models.Team) *GetTeamDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail o k response
func (o *GetTeamDetailOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamDetailDefault Generic error

swagger:response getTeamDetailDefault
*/
type GetTeamDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamDetailDefault creates GetTeamDetailDefault with default headers values
func NewGetTeamDetailDefault(code int) *GetTeamDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get team detail default response
func (o *GetTeamDetailDefault) WithStatusCode(code int) *GetTeamDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get team detail default response
func (o *GetTeamDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get team detail default response
func (o *GetTeamDetailDefault) WithPayload(payload *models.Error) *GetTeamDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get team detail default response
func (o *GetTeamDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
