// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetVEventIDReceptionSplathonReceptionCodeOKCode is the HTTP code returned for type GetVEventIDReceptionSplathonReceptionCodeOK
const GetVEventIDReceptionSplathonReceptionCodeOKCode int = 200

/*GetVEventIDReceptionSplathonReceptionCodeOK Success

swagger:response getVEventIdReceptionSplathonReceptionCodeOK
*/
type GetVEventIDReceptionSplathonReceptionCodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReceptionPartcipantsDataResponse `json:"body,omitempty"`
}

// NewGetVEventIDReceptionSplathonReceptionCodeOK creates GetVEventIDReceptionSplathonReceptionCodeOK with default headers values
func NewGetVEventIDReceptionSplathonReceptionCodeOK() *GetVEventIDReceptionSplathonReceptionCodeOK {

	return &GetVEventIDReceptionSplathonReceptionCodeOK{}
}

// WithPayload adds the payload to the get v event Id reception splathon reception code o k response
func (o *GetVEventIDReceptionSplathonReceptionCodeOK) WithPayload(payload *models.ReceptionPartcipantsDataResponse) *GetVEventIDReceptionSplathonReceptionCodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v event Id reception splathon reception code o k response
func (o *GetVEventIDReceptionSplathonReceptionCodeOK) SetPayload(payload *models.ReceptionPartcipantsDataResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVEventIDReceptionSplathonReceptionCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetVEventIDReceptionSplathonReceptionCodeDefault Generic error

swagger:response getVEventIdReceptionSplathonReceptionCodeDefault
*/
type GetVEventIDReceptionSplathonReceptionCodeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVEventIDReceptionSplathonReceptionCodeDefault creates GetVEventIDReceptionSplathonReceptionCodeDefault with default headers values
func NewGetVEventIDReceptionSplathonReceptionCodeDefault(code int) *GetVEventIDReceptionSplathonReceptionCodeDefault {
	if code <= 0 {
		code = 500
	}

	return &GetVEventIDReceptionSplathonReceptionCodeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v event ID reception splathon reception code default response
func (o *GetVEventIDReceptionSplathonReceptionCodeDefault) WithStatusCode(code int) *GetVEventIDReceptionSplathonReceptionCodeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v event ID reception splathon reception code default response
func (o *GetVEventIDReceptionSplathonReceptionCodeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v event ID reception splathon reception code default response
func (o *GetVEventIDReceptionSplathonReceptionCodeDefault) WithPayload(payload *models.Error) *GetVEventIDReceptionSplathonReceptionCodeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v event ID reception splathon reception code default response
func (o *GetVEventIDReceptionSplathonReceptionCodeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVEventIDReceptionSplathonReceptionCodeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
