// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetParticipantsDataForReceptionOKCode is the HTTP code returned for type GetParticipantsDataForReceptionOK
const GetParticipantsDataForReceptionOKCode int = 200

/*GetParticipantsDataForReceptionOK Success

swagger:response getParticipantsDataForReceptionOK
*/
type GetParticipantsDataForReceptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReceptionPartcipantsDataResponse `json:"body,omitempty"`
}

// NewGetParticipantsDataForReceptionOK creates GetParticipantsDataForReceptionOK with default headers values
func NewGetParticipantsDataForReceptionOK() *GetParticipantsDataForReceptionOK {

	return &GetParticipantsDataForReceptionOK{}
}

// WithPayload adds the payload to the get participants data for reception o k response
func (o *GetParticipantsDataForReceptionOK) WithPayload(payload *models.ReceptionPartcipantsDataResponse) *GetParticipantsDataForReceptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get participants data for reception o k response
func (o *GetParticipantsDataForReceptionOK) SetPayload(payload *models.ReceptionPartcipantsDataResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParticipantsDataForReceptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetParticipantsDataForReceptionDefault Generic error

swagger:response getParticipantsDataForReceptionDefault
*/
type GetParticipantsDataForReceptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetParticipantsDataForReceptionDefault creates GetParticipantsDataForReceptionDefault with default headers values
func NewGetParticipantsDataForReceptionDefault(code int) *GetParticipantsDataForReceptionDefault {
	if code <= 0 {
		code = 500
	}

	return &GetParticipantsDataForReceptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get participants data for reception default response
func (o *GetParticipantsDataForReceptionDefault) WithStatusCode(code int) *GetParticipantsDataForReceptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get participants data for reception default response
func (o *GetParticipantsDataForReceptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get participants data for reception default response
func (o *GetParticipantsDataForReceptionDefault) WithPayload(payload *models.Error) *GetParticipantsDataForReceptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get participants data for reception default response
func (o *GetParticipantsDataForReceptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParticipantsDataForReceptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
