// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetScheduleOKCode is the HTTP code returned for type GetScheduleOK
const GetScheduleOKCode int = 200

/*GetScheduleOK Success

swagger:response getScheduleOK
*/
type GetScheduleOK struct {

	/*
	  In: Body
	*/
	Payload *models.Schedule `json:"body,omitempty"`
}

// NewGetScheduleOK creates GetScheduleOK with default headers values
func NewGetScheduleOK() *GetScheduleOK {

	return &GetScheduleOK{}
}

// WithPayload adds the payload to the get schedule o k response
func (o *GetScheduleOK) WithPayload(payload *models.Schedule) *GetScheduleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule o k response
func (o *GetScheduleOK) SetPayload(payload *models.Schedule) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetScheduleDefault Generic error

swagger:response getScheduleDefault
*/
type GetScheduleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetScheduleDefault creates GetScheduleDefault with default headers values
func NewGetScheduleDefault(code int) *GetScheduleDefault {
	if code <= 0 {
		code = 500
	}

	return &GetScheduleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get schedule default response
func (o *GetScheduleDefault) WithStatusCode(code int) *GetScheduleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get schedule default response
func (o *GetScheduleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get schedule default response
func (o *GetScheduleDefault) WithPayload(payload *models.Error) *GetScheduleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule default response
func (o *GetScheduleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
