// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetParticipantsDataForReceptionHandlerFunc turns a function with the right signature into a get participants data for reception handler
type GetParticipantsDataForReceptionHandlerFunc func(GetParticipantsDataForReceptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParticipantsDataForReceptionHandlerFunc) Handle(params GetParticipantsDataForReceptionParams) middleware.Responder {
	return fn(params)
}

// GetParticipantsDataForReceptionHandler interface for that can handle valid get participants data for reception params
type GetParticipantsDataForReceptionHandler interface {
	Handle(GetParticipantsDataForReceptionParams) middleware.Responder
}

// NewGetParticipantsDataForReception creates a new http.Handler for the get participants data for reception operation
func NewGetParticipantsDataForReception(ctx *middleware.Context, handler GetParticipantsDataForReceptionHandler) *GetParticipantsDataForReception {
	return &GetParticipantsDataForReception{Context: ctx, Handler: handler}
}

/*GetParticipantsDataForReception swagger:route GET /v{eventId}/reception/{splathonReceptionCode} reception admin getParticipantsDataForReception

参加者情報取得API

*/
type GetParticipantsDataForReception struct {
	Context *middleware.Context
	Handler GetParticipantsDataForReceptionHandler
}

func (o *GetParticipantsDataForReception) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetParticipantsDataForReceptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
