// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// ListTeamsOKCode is the HTTP code returned for type ListTeamsOK
const ListTeamsOKCode int = 200

/*ListTeamsOK Success

swagger:response listTeamsOK
*/
type ListTeamsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Teams `json:"body,omitempty"`
}

// NewListTeamsOK creates ListTeamsOK with default headers values
func NewListTeamsOK() *ListTeamsOK {

	return &ListTeamsOK{}
}

// WithPayload adds the payload to the list teams o k response
func (o *ListTeamsOK) WithPayload(payload *models.Teams) *ListTeamsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list teams o k response
func (o *ListTeamsOK) SetPayload(payload *models.Teams) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTeamsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListTeamsDefault Generic error

swagger:response listTeamsDefault
*/
type ListTeamsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTeamsDefault creates ListTeamsDefault with default headers values
func NewListTeamsDefault(code int) *ListTeamsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListTeamsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list teams default response
func (o *ListTeamsDefault) WithStatusCode(code int) *ListTeamsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list teams default response
func (o *ListTeamsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list teams default response
func (o *ListTeamsDefault) WithPayload(payload *models.Error) *ListTeamsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list teams default response
func (o *ListTeamsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTeamsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
