// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListNoticesHandlerFunc turns a function with the right signature into a list notices handler
type ListNoticesHandlerFunc func(ListNoticesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListNoticesHandlerFunc) Handle(params ListNoticesParams) middleware.Responder {
	return fn(params)
}

// ListNoticesHandler interface for that can handle valid list notices params
type ListNoticesHandler interface {
	Handle(ListNoticesParams) middleware.Responder
}

// NewListNotices creates a new http.Handler for the list notices operation
func NewListNotices(ctx *middleware.Context, handler ListNoticesHandler) *ListNotices {
	return &ListNotices{Context: ctx, Handler: handler}
}

/*ListNotices swagger:route GET /v{eventId}/notices listNotices

Return notices

*/
type ListNotices struct {
	Context *middleware.Context
	Handler ListNoticesHandler
}

func (o *ListNotices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListNoticesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
