// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostVEventIDReceptionSplathonReceptionCodeRegisterHandlerFunc turns a function with the right signature into a post v event ID reception splathon reception code register handler
type PostVEventIDReceptionSplathonReceptionCodeRegisterHandlerFunc func(PostVEventIDReceptionSplathonReceptionCodeRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostVEventIDReceptionSplathonReceptionCodeRegisterHandlerFunc) Handle(params PostVEventIDReceptionSplathonReceptionCodeRegisterParams) middleware.Responder {
	return fn(params)
}

// PostVEventIDReceptionSplathonReceptionCodeRegisterHandler interface for that can handle valid post v event ID reception splathon reception code register params
type PostVEventIDReceptionSplathonReceptionCodeRegisterHandler interface {
	Handle(PostVEventIDReceptionSplathonReceptionCodeRegisterParams) middleware.Responder
}

// NewPostVEventIDReceptionSplathonReceptionCodeRegister creates a new http.Handler for the post v event ID reception splathon reception code register operation
func NewPostVEventIDReceptionSplathonReceptionCodeRegister(ctx *middleware.Context, handler PostVEventIDReceptionSplathonReceptionCodeRegisterHandler) *PostVEventIDReceptionSplathonReceptionCodeRegister {
	return &PostVEventIDReceptionSplathonReceptionCodeRegister{Context: ctx, Handler: handler}
}

/*PostVEventIDReceptionSplathonReceptionCodeRegister swagger:route POST /v{eventId}/reception/{splathonReceptionCode}/register reception admin postVEventIdReceptionSplathonReceptionCodeRegister

参加登録API

*/
type PostVEventIDReceptionSplathonReceptionCodeRegister struct {
	Context *middleware.Context
	Handler PostVEventIDReceptionSplathonReceptionCodeRegisterHandler
}

func (o *PostVEventIDReceptionSplathonReceptionCodeRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostVEventIDReceptionSplathonReceptionCodeRegisterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
