// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// PostVEventIDReceptionSplathonReceptionCodeRegisterOKCode is the HTTP code returned for type PostVEventIDReceptionSplathonReceptionCodeRegisterOK
const PostVEventIDReceptionSplathonReceptionCodeRegisterOKCode int = 200

/*PostVEventIDReceptionSplathonReceptionCodeRegisterOK Success

swagger:response postVEventIdReceptionSplathonReceptionCodeRegisterOK
*/
type PostVEventIDReceptionSplathonReceptionCodeRegisterOK struct {
}

// NewPostVEventIDReceptionSplathonReceptionCodeRegisterOK creates PostVEventIDReceptionSplathonReceptionCodeRegisterOK with default headers values
func NewPostVEventIDReceptionSplathonReceptionCodeRegisterOK() *PostVEventIDReceptionSplathonReceptionCodeRegisterOK {

	return &PostVEventIDReceptionSplathonReceptionCodeRegisterOK{}
}

// WriteResponse to the client
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*PostVEventIDReceptionSplathonReceptionCodeRegisterDefault Generic error

swagger:response postVEventIdReceptionSplathonReceptionCodeRegisterDefault
*/
type PostVEventIDReceptionSplathonReceptionCodeRegisterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostVEventIDReceptionSplathonReceptionCodeRegisterDefault creates PostVEventIDReceptionSplathonReceptionCodeRegisterDefault with default headers values
func NewPostVEventIDReceptionSplathonReceptionCodeRegisterDefault(code int) *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault {
	if code <= 0 {
		code = 500
	}

	return &PostVEventIDReceptionSplathonReceptionCodeRegisterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post v event ID reception splathon reception code register default response
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault) WithStatusCode(code int) *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post v event ID reception splathon reception code register default response
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post v event ID reception splathon reception code register default response
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault) WithPayload(payload *models.Error) *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v event ID reception splathon reception code register default response
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostVEventIDReceptionSplathonReceptionCodeRegisterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
