// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RegisterParticipantsHandlerFunc turns a function with the right signature into a register participants handler
type RegisterParticipantsHandlerFunc func(RegisterParticipantsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterParticipantsHandlerFunc) Handle(params RegisterParticipantsParams) middleware.Responder {
	return fn(params)
}

// RegisterParticipantsHandler interface for that can handle valid register participants params
type RegisterParticipantsHandler interface {
	Handle(RegisterParticipantsParams) middleware.Responder
}

// NewRegisterParticipants creates a new http.Handler for the register participants operation
func NewRegisterParticipants(ctx *middleware.Context, handler RegisterParticipantsHandler) *RegisterParticipants {
	return &RegisterParticipants{Context: ctx, Handler: handler}
}

/*RegisterParticipants swagger:route POST /v{eventId}/reception/{splathonReceptionCode}/register reception admin registerParticipants

参加登録API

*/
type RegisterParticipants struct {
	Context *middleware.Context
	Handler RegisterParticipantsHandler
}

func (o *RegisterParticipants) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterParticipantsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
