// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/splathon/splathon-server/swagger/models"
)

// NewUpdateBattleParams creates a new UpdateBattleParams object
// no default values defined in spec.
func NewUpdateBattleParams() UpdateBattleParams {

	return UpdateBattleParams{}
}

// UpdateBattleParams contains all the bound params for the update battle operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateBattle
type UpdateBattleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Battle *models.Battle
	/*
	  Required: true
	  In: path
	*/
	EventID int64
	/*match id
	  Required: true
	  In: path
	*/
	MatchID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateBattleParams() beforehand.
func (o *UpdateBattleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Battle
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("battle", "body"))
			} else {
				res = append(res, errors.NewParseError("battle", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Battle = &body
			}
		}
	} else {
		res = append(res, errors.Required("battle", "body"))
	}
	rEventID, rhkEventID, _ := route.Params.GetOK("eventId")
	if err := o.bindEventID(rEventID, rhkEventID, route.Formats); err != nil {
		res = append(res, err)
	}

	rMatchID, rhkMatchID, _ := route.Params.GetOK("matchId")
	if err := o.bindMatchID(rMatchID, rhkMatchID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEventID binds and validates parameter EventID from path.
func (o *UpdateBattleParams) bindEventID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("eventId", "path", "int64", raw)
	}
	o.EventID = value

	return nil
}

// bindMatchID binds and validates parameter MatchID from path.
func (o *UpdateBattleParams) bindMatchID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("matchId", "path", "int64", raw)
	}
	o.MatchID = value

	return nil
}
