// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// UpdateScheduleOKCode is the HTTP code returned for type UpdateScheduleOK
const UpdateScheduleOKCode int = 200

/*UpdateScheduleOK Success

swagger:response updateScheduleOK
*/
type UpdateScheduleOK struct {
}

// NewUpdateScheduleOK creates UpdateScheduleOK with default headers values
func NewUpdateScheduleOK() *UpdateScheduleOK {

	return &UpdateScheduleOK{}
}

// WriteResponse to the client
func (o *UpdateScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateScheduleDefault Generic error

swagger:response updateScheduleDefault
*/
type UpdateScheduleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateScheduleDefault creates UpdateScheduleDefault with default headers values
func NewUpdateScheduleDefault(code int) *UpdateScheduleDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateScheduleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update schedule default response
func (o *UpdateScheduleDefault) WithStatusCode(code int) *UpdateScheduleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update schedule default response
func (o *UpdateScheduleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update schedule default response
func (o *UpdateScheduleDefault) WithPayload(payload *models.Error) *UpdateScheduleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update schedule default response
func (o *UpdateScheduleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateScheduleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
