runner:
  golint:
    cmd: golint ./...
    format: golint
  govet:
    cmd: go vet ./...
    format: govet
  unused:
    cmd: unused ./...
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank ./...
    errorformat:
      - "%f:%l:%c:%m"
  gosimple:
    cmd: gosimple ./...
    errorformat:
      - "%f:%l:%c: %m"
  staticcheck:
    cmd: staticcheck ./...
    errorformat:
      - "%f:%l:%c: %m"
  misspell:
    cmd: misspell $(git ls-files)
    errorformat:
      - "%f:%l:%c: %m"
  unparam:
    cmd: unparam ./...
    errorformat:
      - "%f:%l:%c: %m"
  revive:
    cmd: revive -config=.revive.toml ./...
    format: golint
  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
