# https://cloud.google.com/appengine/docs/standard/go/config/appref
runtime: go112

handlers:
- url: /.*
  script: auto

automatic_scaling:
  max_instances: 3
  max_idle_instances: 1

includes:
- secret/secret.yaml
- secret/secret_prod.yaml
