version: 2

jobs:
  lint:
    working_directory: ~/reviewdog
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: System information
          command: 'echo "Golang $(go version)"'
      - run: 'curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin'
      - run:
          name: Install Linters
          command: |-
            go get golang.org/x/lint/golint
            go get github.com/kisielk/errcheck
            go get honnef.co/go/tools/cmd/gosimple
            go get honnef.co/go/tools/cmd/staticcheck
            go get honnef.co/go/tools/cmd/unused
            go get github.com/client9/misspell/cmd/misspell
            go get mvdan.cc/unparam
            go get github.com/mgechev/revive
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin
      - run: 'reviewdog -reporter=github-pr-review'
  test:
    working_directory: ~/splathon-server
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: 'go test -v -race ./...'
  coverage:
    working_directory: ~/splathon-server
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: 'go test -coverpkg=./... -coverprofile=coverage.txt ./...'
      - run: 'bash <(curl -s https://codecov.io/bash)'
workflows:
  version: 2
  lint_test:
    jobs:
      - lint
      - test
      - coverage
