version: 2

jobs:
  coverage:
    working_directory: ~/splathon-server
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: 'go test -coverpkg=./... -coverprofile=coverage.txt ./...'
      - run: 'bash <(curl -s https://codecov.io/bash)'
workflows:
  version: 2
  test:
    jobs:
      - coverage
