// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi SplathonAPI
Splathonで使うAPI


    Schemes:
      https
    Host: localhost
    BasePath: /splathon/
    Version: 1.0.0

    Consumes:
    - application/json; charset=utf-8

    Produces:
    - application/json; charset=utf-8

swagger:meta
*/
package restapi
