// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json; charset=utf-8"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Splathonで使うAPI",
    "title": "SplathonAPI",
    "version": "1.0.0"
  },
  "host": "splathon-api-us.appspot.com",
  "basePath": "/splathon/",
  "paths": {
    "/v{eventId}/event": {
      "get": {
        "description": "Return event data",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/list-reception": {
      "get": {
        "tags": [
          "admin"
        ],
        "operationId": "listReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ListReceptionResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/login": {
      "post": {
        "operationId": "login",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/matches/{matchId}": {
      "get": {
        "description": "マッチの詳細を返す。スコアボードとかで使える。",
        "tags": [
          "match"
        ],
        "operationId": "getMatch",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "match id",
            "name": "matchId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Match"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Update a battle data in the match.",
        "tags": [
          "match",
          "admin"
        ],
        "operationId": "updateBattle",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "match id",
            "name": "matchId",
            "in": "path",
            "required": true
          },
          {
            "name": "battle",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Battle"
            }
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/next-match": {
      "get": {
        "description": "次の試合を返す。team_id を指定した場合そのチームの、なければログインしている参加者のチームの 次のマッチをあれば返す。 team_idを指定せず参加者がチームに属して無い場合などはエラー。",
        "tags": [
          "match"
        ],
        "operationId": "getNextMatch",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetNextMatchResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/notices": {
      "get": {
        "description": "Return notices",
        "operationId": "listNotices",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ListNoticesResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/ranking": {
      "get": {
        "description": "予選ランキングを返す。",
        "tags": [
          "ranking"
        ],
        "operationId": "getRanking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Ranking"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception": {
      "get": {
        "tags": [
          "reception"
        ],
        "operationId": "getReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ReceptionResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception/{splathonReceptionCode}": {
      "get": {
        "description": "参加者情報取得API",
        "tags": [
          "reception",
          "admin"
        ],
        "operationId": "getParticipantsDataForReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "ReceptionResponse.splathon.code と同じもの(たぶん内部SlackID).",
            "name": "splathonReceptionCode",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ReceptionPartcipantsDataResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception/{splathonReceptionCode}/complete": {
      "post": {
        "description": "参加登録API",
        "tags": [
          "reception",
          "admin"
        ],
        "operationId": "completeReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "ReceptionResponse.splathon.code と同じもの(たぶん内部SlackID).",
            "name": "splathonReceptionCode",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/results": {
      "get": {
        "description": "リザルト一覧を返す。リザルトと言いつつ終了していない未来のマッチも返す。ゲスト・管理アプリ両方から使う。team_idを指定するとそのチームのみの結果が返ってくる。",
        "tags": [
          "result"
        ],
        "operationId": "getResult",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Results"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/teams": {
      "get": {
        "description": "Return team list",
        "operationId": "listTeams",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Teams"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/teams/{team_id}": {
      "get": {
        "description": "Return detail team data",
        "operationId": "getTeamDetail",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Team"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/update-reception": {
      "post": {
        "tags": [
          "admin"
        ],
        "operationId": "updateReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          },
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateReceptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Battle": {
      "description": "バトル。勝敗などは決まってない状態のこともある。",
      "type": "object",
      "required": [
        "order"
      ],
      "properties": {
        "id": {
          "description": "Battle ID",
          "type": "integer",
          "format": "int64"
        },
        "order": {
          "description": "何戦目か",
          "type": "integer",
          "format": "int32"
        },
        "rule": {
          "$ref": "#/definitions/Rule"
        },
        "stage": {
          "$ref": "#/definitions/Stage"
        },
        "winner": {
          "description": "勝者がどちらか。",
          "type": "string",
          "enum": [
            "alpha",
            "bravo"
          ]
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Event": {
      "type": "object",
      "required": [
        "name",
        "numbering"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "numbering": {
          "type": "integer",
          "format": "int32"
        },
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rule"
          }
        },
        "stages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Stage"
          }
        }
      }
    },
    "GetNextMatchResponse": {
      "type": "object",
      "properties": {
        "next_match": {
          "description": "次のマッチがない、または決まってない場合nullになる。",
          "$ref": "#/definitions/NextMatch"
        }
      }
    },
    "ListNoticesResponse": {
      "type": "object",
      "properties": {
        "notices": {
          "description": "List of notices ordered by reverse chronological order.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Notice"
          }
        }
      }
    },
    "ListReceptionResponse": {
      "type": "object",
      "properties": {
        "participants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ParticipantReception"
          }
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": [
        "user_id",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "user_id": {
          "description": "Slack username (https://splathon.slack.com/account/settings#username)",
          "type": "string"
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "token",
        "is_admin"
      ],
      "properties": {
        "is_admin": {
          "description": "管理者かどうか。(e.g. true なら battle data を送信できる。)",
          "type": "boolean"
        },
        "team": {
          "description": "所属チーム。観戦だとないこともある。またloginユーザーはSlack アカウントを共有している複数の参加者と紐ずいていることもあるが、所属チームは必ず1つ以下。",
          "$ref": "#/definitions/Team"
        },
        "token": {
          "description": "Session API token. Send this token via X-SPLATHON-API-TOKEN HTTP hader. 'X-SPLATHON-API-TOKEN: \u003ctoken\u003e'",
          "type": "string"
        }
      }
    },
    "Match": {
      "type": "object",
      "required": [
        "id",
        "teamAlpha",
        "teamBravo"
      ],
      "properties": {
        "battles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Battle"
          }
        },
        "id": {
          "description": "Match ID",
          "type": "integer",
          "format": "int32"
        },
        "order": {
          "description": "Room内でのマッチの順番",
          "type": "integer",
          "format": "int32"
        },
        "round_name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦. Match APIから読んだときに埋まっている",
          "type": "string"
        },
        "teamAlpha": {
          "$ref": "#/definitions/Team"
        },
        "teamBravo": {
          "$ref": "#/definitions/Team"
        },
        "winner": {
          "description": "勝者がどちらか。または引き分け。",
          "type": "string",
          "enum": [
            "alpha",
            "bravo",
            "draw"
          ]
        }
      }
    },
    "Member": {
      "description": "チーム一覧表示などのAPIではdetailが埋まってることもある",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "detail": {
          "$ref": "#/definitions/MemberDetail"
        },
        "icon": {
          "description": "Slack icon URL",
          "type": "string"
        },
        "id": {
          "description": "Member ID (Slack ID かも?)",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "MemberDetail": {
      "type": "object",
      "properties": {
        "main_weapon": {
          "description": "メインウェポン/好きなブキ",
          "type": "string"
        },
        "rank_clam_blitz": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_rainmaker": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_splat_zones": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_tower_control": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "short_comment": {
          "description": "一言コメント",
          "type": "string"
        }
      }
    },
    "NextMatch": {
      "type": "object",
      "properties": {
        "match_detail": {
          "$ref": "#/definitions/Match"
        },
        "match_order_in_room": {
          "description": "Room内でのマッチの順番",
          "type": "integer",
          "format": "int32"
        },
        "opponent_team": {
          "$ref": "#/definitions/Team"
        },
        "own_team": {
          "$ref": "#/definitions/Team"
        },
        "room": {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "id": {
              "description": "Room ID.",
              "type": "integer",
              "format": "int32"
            },
            "name": {
              "description": "Room name. e.g. A卓",
              "type": "string"
            }
          }
        },
        "round_name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦.",
          "type": "string"
        }
      }
    },
    "Notice": {
      "type": "object",
      "required": [
        "text",
        "timestamp_sec"
      ],
      "properties": {
        "text": {
          "type": "string"
        },
        "timestamp_sec": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ParticipantReception": {
      "type": "object",
      "required": [
        "id",
        "slack_user_id",
        "nickname",
        "fullname_kana",
        "company_name",
        "participant_fee",
        "join_party",
        "is_staff",
        "is_player",
        "has_switch_dock",
        "has_companion"
      ],
      "properties": {
        "company_name": {
          "description": "所属企業名",
          "type": "string"
        },
        "fullname_kana": {
          "description": "カタカナのフルネーム。 e.g. ヤマダタロウ",
          "type": "string"
        },
        "has_companion": {
          "description": "同伴者がいるかどうか。いる場合は用スプレッドシート確認。",
          "type": "boolean"
        },
        "has_switch_dock": {
          "description": "Nintendo Switch doc を持ってきたか",
          "type": "boolean"
        },
        "id": {
          "description": "internal id",
          "type": "integer",
          "format": "int64"
        },
        "is_player": {
          "description": "playerとして参加するかどうか。falseならスタッフか観戦",
          "type": "boolean"
        },
        "is_staff": {
          "description": "スタッフかどうか",
          "type": "boolean"
        },
        "join_party": {
          "description": "懇親会に参加するか否か",
          "type": "boolean"
        },
        "nickname": {
          "description": "ハンドルネーム。 e.g. みーくん",
          "type": "string"
        },
        "participant_fee": {
          "description": "合計参加費(円)",
          "type": "integer",
          "format": "int32"
        },
        "reception": {
          "$ref": "#/definitions/Reception"
        },
        "slack_user_id": {
          "description": "Slack ID",
          "type": "string"
        },
        "team_id": {
          "description": "チームID(一応)",
          "type": "integer",
          "format": "int64"
        },
        "team_name": {
          "description": "チーム名",
          "type": "string"
        }
      }
    },
    "Rank": {
      "type": "object",
      "required": [
        "rank",
        "team",
        "point"
      ],
      "properties": {
        "num_of_matches": {
          "description": "何戦こなしたか。",
          "type": "integer",
          "format": "int32"
        },
        "omwp": {
          "description": "OMWP (Opponent Match Win Percentage)",
          "type": "number"
        },
        "point": {
          "description": "勝ち点",
          "type": "integer",
          "format": "int32"
        },
        "rank": {
          "description": "順位",
          "type": "integer",
          "format": "int32"
        },
        "team": {
          "description": "member も fill される",
          "$ref": "#/definitions/Team"
        }
      }
    },
    "Ranking": {
      "description": "予選ランキング",
      "type": "object",
      "properties": {
        "rank_time": {
          "description": "ランキング計算時点の説明。e.g. 予選第2ラウンド終了時",
          "type": "string"
        },
        "rankings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rank"
          }
        }
      }
    },
    "Reception": {
      "type": "object",
      "required": [
        "id",
        "participant_id",
        "created_at_timestamp_sec",
        "updated_at_timestamp_sec"
      ],
      "properties": {
        "created_at_timestamp_sec": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "memo": {
          "type": "string"
        },
        "participant_id": {
          "type": "integer",
          "format": "int64"
        },
        "updated_at_timestamp_sec": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ReceptionCode": {
      "description": "ビル入館情報/Splathon会場受付情報",
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "code_type": {
          "type": "string",
          "enum": [
            "qrcode",
            "barcode"
          ]
        },
        "description": {
          "description": "入場の説明",
          "type": "string"
        },
        "name": {
          "description": "Splathon会場入場コード/XXXビル入館コード",
          "type": "string"
        },
        "qrcode_img": {
          "description": "Image URL of QR code",
          "type": "string"
        },
        "short_text": {
          "description": "コードの説明",
          "type": "string"
        }
      }
    },
    "ReceptionPartcipantsDataResponse": {
      "type": "object",
      "properties": {
        "description": {
          "description": "受付の仕方の説明や注意点などのフリーテキスト。",
          "type": "string"
        },
        "participants": {
          "description": "1つのSlackIDで複数の参加者をカバーしている。また participants とは別に参加者情報のない同伴者が存在する可能性があり、 もしいる場合は has_companion flag が true となる",
          "type": "array",
          "items": {
            "$ref": "#/definitions/ParticipantReception"
          }
        },
        "slack_internal_id": {
          "description": "参加者の Slack Internal ID",
          "type": "string"
        }
      }
    },
    "ReceptionResponse": {
      "type": "object",
      "properties": {
        "building": {
          "description": "ビル入館情報",
          "$ref": "#/definitions/ReceptionCode"
        },
        "splathon": {
          "description": "Splathon会場受付情報",
          "$ref": "#/definitions/ReceptionCode"
        }
      }
    },
    "Results": {
      "description": "予選/決勝Tのリザルト。予選/決勝Tは同じ構造なのでフラットにできるがクライアントがトーナメント表だせる拡張性持たせるために別フィールドで持つ。",
      "type": "object",
      "properties": {
        "qualifiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Round"
          }
        },
        "tournament": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Round"
          }
        }
      }
    },
    "Room": {
      "description": "Roomごとのマッチ",
      "type": "object",
      "required": [
        "name",
        "matches"
      ],
      "properties": {
        "id": {
          "description": "Room ID.",
          "type": "integer",
          "format": "int32"
        },
        "matches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Match"
          }
        },
        "name": {
          "description": "Room name. e.g. A卓",
          "type": "string"
        }
      }
    },
    "Round": {
      "description": "予選/決勝Tラウンド両方扱う。",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦",
          "type": "string"
        },
        "rooms": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Room"
          }
        },
        "round": {
          "description": "何ラウンドか。i.e. 予選第Nラウンド, 決勝T N回戦",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Rule": {
      "type": "object",
      "required": [
        "key"
      ],
      "properties": {
        "key": {
          "description": "Rule key. ref: https://splatoon2.ink/data/locale/ja.json",
          "type": "string",
          "enum": [
            "turf_war",
            "splat_zones",
            "tower_control",
            "rainmaker",
            "clam_blitz"
          ]
        },
        "name": {
          "description": "Localized rule name.",
          "type": "string"
        }
      }
    },
    "Stage": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "description": "Stage ID. ref: https://splatoon2.ink/data/locale/ja.json",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "description": "Localized stage name.",
          "type": "string"
        }
      }
    },
    "Team": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "description": "Team ID",
          "type": "integer",
          "format": "int32"
        },
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Member"
          }
        },
        "name": {
          "type": "string"
        },
        "short_comment": {
          "description": "Team の大会にむけての意気込みコメント",
          "type": "string"
        }
      }
    },
    "Teams": {
      "type": "object",
      "properties": {
        "teams": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Team"
          }
        }
      }
    },
    "UpdateReceptionRequest": {
      "type": "object",
      "required": [
        "participant",
        "complete"
      ],
      "properties": {
        "complete": {
          "type": "boolean"
        },
        "participant": {
          "$ref": "#/definitions/ParticipantReception"
        }
      }
    }
  },
  "tags": [
    {
      "description": "リザルト一覧",
      "name": "result"
    },
    {
      "description": "マッチ",
      "name": "match"
    },
    {
      "description": "予選ランキング",
      "name": "ranking"
    },
    {
      "description": "管理機能",
      "name": "admin"
    },
    {
      "description": "受付機能",
      "name": "reception"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json; charset=utf-8"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Splathonで使うAPI",
    "title": "SplathonAPI",
    "version": "1.0.0"
  },
  "host": "splathon-api-us.appspot.com",
  "basePath": "/splathon/",
  "paths": {
    "/v{eventId}/event": {
      "get": {
        "description": "Return event data",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/list-reception": {
      "get": {
        "tags": [
          "admin"
        ],
        "operationId": "listReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ListReceptionResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/login": {
      "post": {
        "operationId": "login",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/matches/{matchId}": {
      "get": {
        "description": "マッチの詳細を返す。スコアボードとかで使える。",
        "tags": [
          "match"
        ],
        "operationId": "getMatch",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "match id",
            "name": "matchId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Match"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Update a battle data in the match.",
        "tags": [
          "match",
          "admin"
        ],
        "operationId": "updateBattle",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "match id",
            "name": "matchId",
            "in": "path",
            "required": true
          },
          {
            "name": "battle",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Battle"
            }
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/next-match": {
      "get": {
        "description": "次の試合を返す。team_id を指定した場合そのチームの、なければログインしている参加者のチームの 次のマッチをあれば返す。 team_idを指定せず参加者がチームに属して無い場合などはエラー。",
        "tags": [
          "match"
        ],
        "operationId": "getNextMatch",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetNextMatchResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/notices": {
      "get": {
        "description": "Return notices",
        "operationId": "listNotices",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ListNoticesResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/ranking": {
      "get": {
        "description": "予選ランキングを返す。",
        "tags": [
          "ranking"
        ],
        "operationId": "getRanking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Ranking"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception": {
      "get": {
        "tags": [
          "reception"
        ],
        "operationId": "getReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ReceptionResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception/{splathonReceptionCode}": {
      "get": {
        "description": "参加者情報取得API",
        "tags": [
          "reception",
          "admin"
        ],
        "operationId": "getParticipantsDataForReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "ReceptionResponse.splathon.code と同じもの(たぶん内部SlackID).",
            "name": "splathonReceptionCode",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ReceptionPartcipantsDataResponse"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/reception/{splathonReceptionCode}/complete": {
      "post": {
        "description": "参加登録API",
        "tags": [
          "reception",
          "admin"
        ],
        "operationId": "completeReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "ReceptionResponse.splathon.code と同じもの(たぶん内部SlackID).",
            "name": "splathonReceptionCode",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/results": {
      "get": {
        "description": "リザルト一覧を返す。リザルトと言いつつ終了していない未来のマッチも返す。ゲスト・管理アプリ両方から使う。team_idを指定するとそのチームのみの結果が返ってくる。",
        "tags": [
          "result"
        ],
        "operationId": "getResult",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Results"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/teams": {
      "get": {
        "description": "Return team list",
        "operationId": "listTeams",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Teams"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/teams/{team_id}": {
      "get": {
        "description": "Return detail team data",
        "operationId": "getTeamDetail",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "team id",
            "name": "team_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Team"
            }
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v{eventId}/update-reception": {
      "post": {
        "tags": [
          "admin"
        ],
        "operationId": "updateReception",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "X-SPLATHON-API-TOKEN",
            "in": "header",
            "required": true
          },
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateReceptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "Generic error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Battle": {
      "description": "バトル。勝敗などは決まってない状態のこともある。",
      "type": "object",
      "required": [
        "order"
      ],
      "properties": {
        "id": {
          "description": "Battle ID",
          "type": "integer",
          "format": "int64"
        },
        "order": {
          "description": "何戦目か",
          "type": "integer",
          "format": "int32"
        },
        "rule": {
          "$ref": "#/definitions/Rule"
        },
        "stage": {
          "$ref": "#/definitions/Stage"
        },
        "winner": {
          "description": "勝者がどちらか。",
          "type": "string",
          "enum": [
            "alpha",
            "bravo"
          ]
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Event": {
      "type": "object",
      "required": [
        "name",
        "numbering"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "numbering": {
          "type": "integer",
          "format": "int32"
        },
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rule"
          }
        },
        "stages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Stage"
          }
        }
      }
    },
    "GetNextMatchResponse": {
      "type": "object",
      "properties": {
        "next_match": {
          "description": "次のマッチがない、または決まってない場合nullになる。",
          "$ref": "#/definitions/NextMatch"
        }
      }
    },
    "ListNoticesResponse": {
      "type": "object",
      "properties": {
        "notices": {
          "description": "List of notices ordered by reverse chronological order.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Notice"
          }
        }
      }
    },
    "ListReceptionResponse": {
      "type": "object",
      "properties": {
        "participants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ParticipantReception"
          }
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": [
        "user_id",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "user_id": {
          "description": "Slack username (https://splathon.slack.com/account/settings#username)",
          "type": "string"
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "token",
        "is_admin"
      ],
      "properties": {
        "is_admin": {
          "description": "管理者かどうか。(e.g. true なら battle data を送信できる。)",
          "type": "boolean"
        },
        "team": {
          "description": "所属チーム。観戦だとないこともある。またloginユーザーはSlack アカウントを共有している複数の参加者と紐ずいていることもあるが、所属チームは必ず1つ以下。",
          "$ref": "#/definitions/Team"
        },
        "token": {
          "description": "Session API token. Send this token via X-SPLATHON-API-TOKEN HTTP hader. 'X-SPLATHON-API-TOKEN: \u003ctoken\u003e'",
          "type": "string"
        }
      }
    },
    "Match": {
      "type": "object",
      "required": [
        "id",
        "teamAlpha",
        "teamBravo"
      ],
      "properties": {
        "battles": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Battle"
          }
        },
        "id": {
          "description": "Match ID",
          "type": "integer",
          "format": "int32"
        },
        "order": {
          "description": "Room内でのマッチの順番",
          "type": "integer",
          "format": "int32"
        },
        "round_name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦. Match APIから読んだときに埋まっている",
          "type": "string"
        },
        "teamAlpha": {
          "$ref": "#/definitions/Team"
        },
        "teamBravo": {
          "$ref": "#/definitions/Team"
        },
        "winner": {
          "description": "勝者がどちらか。または引き分け。",
          "type": "string",
          "enum": [
            "alpha",
            "bravo",
            "draw"
          ]
        }
      }
    },
    "Member": {
      "description": "チーム一覧表示などのAPIではdetailが埋まってることもある",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "detail": {
          "$ref": "#/definitions/MemberDetail"
        },
        "icon": {
          "description": "Slack icon URL",
          "type": "string"
        },
        "id": {
          "description": "Member ID (Slack ID かも?)",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "MemberDetail": {
      "type": "object",
      "properties": {
        "main_weapon": {
          "description": "メインウェポン/好きなブキ",
          "type": "string"
        },
        "rank_clam_blitz": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_rainmaker": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_splat_zones": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "rank_tower_control": {
          "description": "A+, X (2401~2500)",
          "type": "string"
        },
        "short_comment": {
          "description": "一言コメント",
          "type": "string"
        }
      }
    },
    "NextMatch": {
      "type": "object",
      "properties": {
        "match_detail": {
          "$ref": "#/definitions/Match"
        },
        "match_order_in_room": {
          "description": "Room内でのマッチの順番",
          "type": "integer",
          "format": "int32"
        },
        "opponent_team": {
          "$ref": "#/definitions/Team"
        },
        "own_team": {
          "$ref": "#/definitions/Team"
        },
        "room": {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "id": {
              "description": "Room ID.",
              "type": "integer",
              "format": "int32"
            },
            "name": {
              "description": "Room name. e.g. A卓",
              "type": "string"
            }
          }
        },
        "round_name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦.",
          "type": "string"
        }
      }
    },
    "Notice": {
      "type": "object",
      "required": [
        "text",
        "timestamp_sec"
      ],
      "properties": {
        "text": {
          "type": "string"
        },
        "timestamp_sec": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ParticipantReception": {
      "type": "object",
      "required": [
        "id",
        "slack_user_id",
        "nickname",
        "fullname_kana",
        "company_name",
        "participant_fee",
        "join_party",
        "is_staff",
        "is_player",
        "has_switch_dock",
        "has_companion"
      ],
      "properties": {
        "company_name": {
          "description": "所属企業名",
          "type": "string"
        },
        "fullname_kana": {
          "description": "カタカナのフルネーム。 e.g. ヤマダタロウ",
          "type": "string"
        },
        "has_companion": {
          "description": "同伴者がいるかどうか。いる場合は用スプレッドシート確認。",
          "type": "boolean"
        },
        "has_switch_dock": {
          "description": "Nintendo Switch doc を持ってきたか",
          "type": "boolean"
        },
        "id": {
          "description": "internal id",
          "type": "integer",
          "format": "int64"
        },
        "is_player": {
          "description": "playerとして参加するかどうか。falseならスタッフか観戦",
          "type": "boolean"
        },
        "is_staff": {
          "description": "スタッフかどうか",
          "type": "boolean"
        },
        "join_party": {
          "description": "懇親会に参加するか否か",
          "type": "boolean"
        },
        "nickname": {
          "description": "ハンドルネーム。 e.g. みーくん",
          "type": "string"
        },
        "participant_fee": {
          "description": "合計参加費(円)",
          "type": "integer",
          "format": "int32"
        },
        "reception": {
          "$ref": "#/definitions/Reception"
        },
        "slack_user_id": {
          "description": "Slack ID",
          "type": "string"
        },
        "team_id": {
          "description": "チームID(一応)",
          "type": "integer",
          "format": "int64"
        },
        "team_name": {
          "description": "チーム名",
          "type": "string"
        }
      }
    },
    "Rank": {
      "type": "object",
      "required": [
        "rank",
        "team",
        "point"
      ],
      "properties": {
        "num_of_matches": {
          "description": "何戦こなしたか。",
          "type": "integer",
          "format": "int32"
        },
        "omwp": {
          "description": "OMWP (Opponent Match Win Percentage)",
          "type": "number"
        },
        "point": {
          "description": "勝ち点",
          "type": "integer",
          "format": "int32"
        },
        "rank": {
          "description": "順位",
          "type": "integer",
          "format": "int32"
        },
        "team": {
          "description": "member も fill される",
          "$ref": "#/definitions/Team"
        }
      }
    },
    "Ranking": {
      "description": "予選ランキング",
      "type": "object",
      "properties": {
        "rank_time": {
          "description": "ランキング計算時点の説明。e.g. 予選第2ラウンド終了時",
          "type": "string"
        },
        "rankings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Rank"
          }
        }
      }
    },
    "Reception": {
      "type": "object",
      "required": [
        "id",
        "participant_id",
        "created_at_timestamp_sec",
        "updated_at_timestamp_sec"
      ],
      "properties": {
        "created_at_timestamp_sec": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "memo": {
          "type": "string"
        },
        "participant_id": {
          "type": "integer",
          "format": "int64"
        },
        "updated_at_timestamp_sec": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ReceptionCode": {
      "description": "ビル入館情報/Splathon会場受付情報",
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "code_type": {
          "type": "string",
          "enum": [
            "qrcode",
            "barcode"
          ]
        },
        "description": {
          "description": "入場の説明",
          "type": "string"
        },
        "name": {
          "description": "Splathon会場入場コード/XXXビル入館コード",
          "type": "string"
        },
        "qrcode_img": {
          "description": "Image URL of QR code",
          "type": "string"
        },
        "short_text": {
          "description": "コードの説明",
          "type": "string"
        }
      }
    },
    "ReceptionPartcipantsDataResponse": {
      "type": "object",
      "properties": {
        "description": {
          "description": "受付の仕方の説明や注意点などのフリーテキスト。",
          "type": "string"
        },
        "participants": {
          "description": "1つのSlackIDで複数の参加者をカバーしている。また participants とは別に参加者情報のない同伴者が存在する可能性があり、 もしいる場合は has_companion flag が true となる",
          "type": "array",
          "items": {
            "$ref": "#/definitions/ParticipantReception"
          }
        },
        "slack_internal_id": {
          "description": "参加者の Slack Internal ID",
          "type": "string"
        }
      }
    },
    "ReceptionResponse": {
      "type": "object",
      "properties": {
        "building": {
          "description": "ビル入館情報",
          "$ref": "#/definitions/ReceptionCode"
        },
        "splathon": {
          "description": "Splathon会場受付情報",
          "$ref": "#/definitions/ReceptionCode"
        }
      }
    },
    "Results": {
      "description": "予選/決勝Tのリザルト。予選/決勝Tは同じ構造なのでフラットにできるがクライアントがトーナメント表だせる拡張性持たせるために別フィールドで持つ。",
      "type": "object",
      "properties": {
        "qualifiers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Round"
          }
        },
        "tournament": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Round"
          }
        }
      }
    },
    "Room": {
      "description": "Roomごとのマッチ",
      "type": "object",
      "required": [
        "name",
        "matches"
      ],
      "properties": {
        "id": {
          "description": "Room ID.",
          "type": "integer",
          "format": "int32"
        },
        "matches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Match"
          }
        },
        "name": {
          "description": "Room name. e.g. A卓",
          "type": "string"
        }
      }
    },
    "Round": {
      "description": "予選/決勝Tラウンド両方扱う。",
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "ラウンド名。e.g. 予選第1ラウンド, 決勝T1回戦, 決勝戦",
          "type": "string"
        },
        "rooms": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Room"
          }
        },
        "round": {
          "description": "何ラウンドか。i.e. 予選第Nラウンド, 決勝T N回戦",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Rule": {
      "type": "object",
      "required": [
        "key"
      ],
      "properties": {
        "key": {
          "description": "Rule key. ref: https://splatoon2.ink/data/locale/ja.json",
          "type": "string",
          "enum": [
            "turf_war",
            "splat_zones",
            "tower_control",
            "rainmaker",
            "clam_blitz"
          ]
        },
        "name": {
          "description": "Localized rule name.",
          "type": "string"
        }
      }
    },
    "Stage": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "description": "Stage ID. ref: https://splatoon2.ink/data/locale/ja.json",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "description": "Localized stage name.",
          "type": "string"
        }
      }
    },
    "Team": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "description": "Team ID",
          "type": "integer",
          "format": "int32"
        },
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Member"
          }
        },
        "name": {
          "type": "string"
        },
        "short_comment": {
          "description": "Team の大会にむけての意気込みコメント",
          "type": "string"
        }
      }
    },
    "Teams": {
      "type": "object",
      "properties": {
        "teams": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Team"
          }
        }
      }
    },
    "UpdateReceptionRequest": {
      "type": "object",
      "required": [
        "participant",
        "complete"
      ],
      "properties": {
        "complete": {
          "type": "boolean"
        },
        "participant": {
          "$ref": "#/definitions/ParticipantReception"
        }
      }
    }
  },
  "tags": [
    {
      "description": "リザルト一覧",
      "name": "result"
    },
    {
      "description": "マッチ",
      "name": "match"
    },
    {
      "description": "予選ランキング",
      "name": "ranking"
    },
    {
      "description": "管理機能",
      "name": "admin"
    },
    {
      "description": "受付機能",
      "name": "reception"
    }
  ]
}`))
}
