// Code generated by go-swagger; DO NOT EDIT.

package reception

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetReceptionOKCode is the HTTP code returned for type GetReceptionOK
const GetReceptionOKCode int = 200

/*GetReceptionOK Success

swagger:response getReceptionOK
*/
type GetReceptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReceptionResponse `json:"body,omitempty"`
}

// NewGetReceptionOK creates GetReceptionOK with default headers values
func NewGetReceptionOK() *GetReceptionOK {

	return &GetReceptionOK{}
}

// WithPayload adds the payload to the get reception o k response
func (o *GetReceptionOK) WithPayload(payload *models.ReceptionResponse) *GetReceptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reception o k response
func (o *GetReceptionOK) SetPayload(payload *models.ReceptionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetReceptionDefault Generic error

swagger:response getReceptionDefault
*/
type GetReceptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReceptionDefault creates GetReceptionDefault with default headers values
func NewGetReceptionDefault(code int) *GetReceptionDefault {
	if code <= 0 {
		code = 500
	}

	return &GetReceptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get reception default response
func (o *GetReceptionDefault) WithStatusCode(code int) *GetReceptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get reception default response
func (o *GetReceptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get reception default response
func (o *GetReceptionDefault) WithPayload(payload *models.Error) *GetReceptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reception default response
func (o *GetReceptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReceptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
