// Code generated by go-swagger; DO NOT EDIT.

package reception

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReceptionHandlerFunc turns a function with the right signature into a get reception handler
type GetReceptionHandlerFunc func(GetReceptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReceptionHandlerFunc) Handle(params GetReceptionParams) middleware.Responder {
	return fn(params)
}

// GetReceptionHandler interface for that can handle valid get reception params
type GetReceptionHandler interface {
	Handle(GetReceptionParams) middleware.Responder
}

// NewGetReception creates a new http.Handler for the get reception operation
func NewGetReception(ctx *middleware.Context, handler GetReceptionHandler) *GetReception {
	return &GetReception{Context: ctx, Handler: handler}
}

/*GetReception swagger:route GET /v{eventId}/reception reception getReception

GetReception get reception API

*/
type GetReception struct {
	Context *middleware.Context
	Handler GetReceptionHandler
}

func (o *GetReception) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReceptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
