// Code generated by go-swagger; DO NOT EDIT.

package ranking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetRankingOKCode is the HTTP code returned for type GetRankingOK
const GetRankingOKCode int = 200

/*GetRankingOK Success

swagger:response getRankingOK
*/
type GetRankingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ranking `json:"body,omitempty"`
}

// NewGetRankingOK creates GetRankingOK with default headers values
func NewGetRankingOK() *GetRankingOK {

	return &GetRankingOK{}
}

// WithPayload adds the payload to the get ranking o k response
func (o *GetRankingOK) WithPayload(payload *models.Ranking) *GetRankingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ranking o k response
func (o *GetRankingOK) SetPayload(payload *models.Ranking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRankingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRankingDefault Generic error

swagger:response getRankingDefault
*/
type GetRankingDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRankingDefault creates GetRankingDefault with default headers values
func NewGetRankingDefault(code int) *GetRankingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRankingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get ranking default response
func (o *GetRankingDefault) WithStatusCode(code int) *GetRankingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get ranking default response
func (o *GetRankingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get ranking default response
func (o *GetRankingDefault) WithPayload(payload *models.Error) *GetRankingDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ranking default response
func (o *GetRankingDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRankingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
