// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddTournamentRoundRequest add tournament round request
// swagger:model AddTournamentRoundRequest
type AddTournamentRoundRequest struct {

	// matches
	// Required: true
	Matches []*NewMatchRequest `json:"matches"`

	// round
	// Required: true
	Round *int32 `json:"round"`

	// round name
	// Required: true
	RoundName *string `json:"round_name"`
}

// Validate validates this add tournament round request
func (m *AddTournamentRoundRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatches(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRound(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoundName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddTournamentRoundRequest) validateMatches(formats strfmt.Registry) error {

	if err := validate.Required("matches", "body", m.Matches); err != nil {
		return err
	}

	for i := 0; i < len(m.Matches); i++ {
		if swag.IsZero(m.Matches[i]) { // not required
			continue
		}

		if m.Matches[i] != nil {
			if err := m.Matches[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("matches" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AddTournamentRoundRequest) validateRound(formats strfmt.Registry) error {

	if err := validate.Required("round", "body", m.Round); err != nil {
		return err
	}

	return nil
}

func (m *AddTournamentRoundRequest) validateRoundName(formats strfmt.Registry) error {

	if err := validate.Required("round_name", "body", m.RoundName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddTournamentRoundRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddTournamentRoundRequest) UnmarshalBinary(b []byte) error {
	var res AddTournamentRoundRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
