// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Battle バトル。勝敗などは決まってない状態のこともある。
// swagger:model Battle
type Battle struct {

	// Battle ID
	ID int64 `json:"id,omitempty"`

	// 何戦目か
	// Required: true
	Order *int32 `json:"order"`

	// rule
	Rule *BattleRule `json:"rule,omitempty"`

	// stage
	Stage *BattleStage `json:"stage,omitempty"`

	// 勝者がどちらか。
	// Enum: [alpha bravo]
	Winner string `json:"winner,omitempty"`
}

// Validate validates this battle
func (m *Battle) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrder(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRule(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWinner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Battle) validateOrder(formats strfmt.Registry) error {

	if err := validate.Required("order", "body", m.Order); err != nil {
		return err
	}

	return nil
}

func (m *Battle) validateRule(formats strfmt.Registry) error {

	if swag.IsZero(m.Rule) { // not required
		return nil
	}

	if m.Rule != nil {
		if err := m.Rule.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rule")
			}
			return err
		}
	}

	return nil
}

func (m *Battle) validateStage(formats strfmt.Registry) error {

	if swag.IsZero(m.Stage) { // not required
		return nil
	}

	if m.Stage != nil {
		if err := m.Stage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stage")
			}
			return err
		}
	}

	return nil
}

var battleTypeWinnerPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["alpha","bravo"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		battleTypeWinnerPropEnum = append(battleTypeWinnerPropEnum, v)
	}
}

const (

	// BattleWinnerAlpha captures enum value "alpha"
	BattleWinnerAlpha string = "alpha"

	// BattleWinnerBravo captures enum value "bravo"
	BattleWinnerBravo string = "bravo"
)

// prop value enum
func (m *Battle) validateWinnerEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, battleTypeWinnerPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Battle) validateWinner(formats strfmt.Registry) error {

	if swag.IsZero(m.Winner) { // not required
		return nil
	}

	// value enum
	if err := m.validateWinnerEnum("winner", "body", m.Winner); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Battle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Battle) UnmarshalBinary(b []byte) error {
	var res Battle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BattleRule battle rule
// swagger:model BattleRule
type BattleRule struct {

	// Rule key. ref: https://splatoon2.ink/data/locale/ja.json
	// Required: true
	// Enum: [turf_war splat_zones tower_control rainmaker clam_blitz]
	Key *string `json:"key"`

	// Localized rule name.
	Name string `json:"name,omitempty"`
}

// Validate validates this battle rule
func (m *BattleRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var battleRuleTypeKeyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["turf_war","splat_zones","tower_control","rainmaker","clam_blitz"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		battleRuleTypeKeyPropEnum = append(battleRuleTypeKeyPropEnum, v)
	}
}

const (

	// BattleRuleKeyTurfWar captures enum value "turf_war"
	BattleRuleKeyTurfWar string = "turf_war"

	// BattleRuleKeySplatZones captures enum value "splat_zones"
	BattleRuleKeySplatZones string = "splat_zones"

	// BattleRuleKeyTowerControl captures enum value "tower_control"
	BattleRuleKeyTowerControl string = "tower_control"

	// BattleRuleKeyRainmaker captures enum value "rainmaker"
	BattleRuleKeyRainmaker string = "rainmaker"

	// BattleRuleKeyClamBlitz captures enum value "clam_blitz"
	BattleRuleKeyClamBlitz string = "clam_blitz"
)

// prop value enum
func (m *BattleRule) validateKeyEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, battleRuleTypeKeyPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *BattleRule) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("rule"+"."+"key", "body", m.Key); err != nil {
		return err
	}

	// value enum
	if err := m.validateKeyEnum("rule"+"."+"key", "body", *m.Key); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BattleRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BattleRule) UnmarshalBinary(b []byte) error {
	var res BattleRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BattleStage battle stage
// swagger:model BattleStage
type BattleStage struct {

	// Stage ID. ref: https://splatoon2.ink/data/locale/ja.json
	// Required: true
	ID *int32 `json:"id"`

	// Localized stage name.
	Name string `json:"name,omitempty"`
}

// Validate validates this battle stage
func (m *BattleStage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BattleStage) validateID(formats strfmt.Registry) error {

	if err := validate.Required("stage"+"."+"id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BattleStage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BattleStage) UnmarshalBinary(b []byte) error {
	var res BattleStage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
