// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetNextMatchResponse get next match response
// swagger:model GetNextMatchResponse
type GetNextMatchResponse struct {

	// 次のマッチがない、または決まってない場合nullになる。
	NextMatch *NextMatch `json:"next_match,omitempty"`
}

// Validate validates this get next match response
func (m *GetNextMatchResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextMatch(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetNextMatchResponse) validateNextMatch(formats strfmt.Registry) error {

	if swag.IsZero(m.NextMatch) { // not required
		return nil
	}

	if m.NextMatch != nil {
		if err := m.NextMatch.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("next_match")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetNextMatchResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNextMatchResponse) UnmarshalBinary(b []byte) error {
	var res GetNextMatchResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
