// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MemberDetail member detail
// swagger:model MemberDetail
type MemberDetail struct {

	// メインウェポン/好きなブキ
	MainWeapon string `json:"main_weapon,omitempty"`

	// A+, X (2401~2500)
	RankClamBlitz string `json:"rank_clam_blitz,omitempty"`

	// A+, X (2401~2500)
	RankRainmaker string `json:"rank_rainmaker,omitempty"`

	// A+, X (2401~2500)
	RankSplatZones string `json:"rank_splat_zones,omitempty"`

	// A+, X (2401~2500)
	RankTowerControl string `json:"rank_tower_control,omitempty"`

	// 一言コメント
	ShortComment string `json:"short_comment,omitempty"`
}

// Validate validates this member detail
func (m *MemberDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MemberDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MemberDetail) UnmarshalBinary(b []byte) error {
	var res MemberDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
