// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ReceptionResponse reception response
// swagger:model ReceptionResponse
type ReceptionResponse struct {

	// ビル入館情報
	Building *ReceptionCode `json:"building,omitempty"`

	// Splathon会場受付情報
	Splathon *ReceptionCode `json:"splathon,omitempty"`
}

// Validate validates this reception response
func (m *ReceptionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuilding(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSplathon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReceptionResponse) validateBuilding(formats strfmt.Registry) error {

	if swag.IsZero(m.Building) { // not required
		return nil
	}

	if m.Building != nil {
		if err := m.Building.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("building")
			}
			return err
		}
	}

	return nil
}

func (m *ReceptionResponse) validateSplathon(formats strfmt.Registry) error {

	if swag.IsZero(m.Splathon) { // not required
		return nil
	}

	if m.Splathon != nil {
		if err := m.Splathon.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("splathon")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReceptionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReceptionResponse) UnmarshalBinary(b []byte) error {
	var res ReceptionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
