// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ScheduleEntry schedule entry
// swagger:model ScheduleEntry
type ScheduleEntry struct {

	// duration sec
	DurationSec int64 `json:"duration_sec,omitempty"`

	// Unix timestamp in seconds.
	StartTimestampSec int64 `json:"start_timestamp_sec,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this schedule entry
func (m *ScheduleEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScheduleEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScheduleEntry) UnmarshalBinary(b []byte) error {
	var res ScheduleEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
