// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UpdateReleaseQualifierRequest update release qualifier request
// swagger:model UpdateReleaseQualifierRequest
type UpdateReleaseQualifierRequest struct {

	// round
	Round int32 `json:"round,omitempty"`
}

// Validate validates this update release qualifier request
func (m *UpdateReleaseQualifierRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateReleaseQualifierRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateReleaseQualifierRequest) UnmarshalBinary(b []byte) error {
	var res UpdateReleaseQualifierRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
