// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateNewQualifierHandlerFunc turns a function with the right signature into a create new qualifier handler
type CreateNewQualifierHandlerFunc func(CreateNewQualifierParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateNewQualifierHandlerFunc) Handle(params CreateNewQualifierParams) middleware.Responder {
	return fn(params)
}

// CreateNewQualifierHandler interface for that can handle valid create new qualifier params
type CreateNewQualifierHandler interface {
	Handle(CreateNewQualifierParams) middleware.Responder
}

// NewCreateNewQualifier creates a new http.Handler for the create new qualifier operation
func NewCreateNewQualifier(ctx *middleware.Context, handler CreateNewQualifierHandler) *CreateNewQualifier {
	return &CreateNewQualifier{Context: ctx, Handler: handler}
}

/*CreateNewQualifier swagger:route POST /v{eventId}/qualifier admin createNewQualifier

CreateNewQualifier create new qualifier API

*/
type CreateNewQualifier struct {
	Context *middleware.Context
	Handler CreateNewQualifierHandler
}

func (o *CreateNewQualifier) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateNewQualifierParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
