// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteQualifierHandlerFunc turns a function with the right signature into a delete qualifier handler
type DeleteQualifierHandlerFunc func(DeleteQualifierParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteQualifierHandlerFunc) Handle(params DeleteQualifierParams) middleware.Responder {
	return fn(params)
}

// DeleteQualifierHandler interface for that can handle valid delete qualifier params
type DeleteQualifierHandler interface {
	Handle(DeleteQualifierParams) middleware.Responder
}

// NewDeleteQualifier creates a new http.Handler for the delete qualifier operation
func NewDeleteQualifier(ctx *middleware.Context, handler DeleteQualifierHandler) *DeleteQualifier {
	return &DeleteQualifier{Context: ctx, Handler: handler}
}

/*DeleteQualifier swagger:route POST /v{eventId}/delete-qualifier admin deleteQualifier

DeleteQualifier delete qualifier API

*/
type DeleteQualifier struct {
	Context *middleware.Context
	Handler DeleteQualifierHandler
}

func (o *DeleteQualifier) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteQualifierParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
