// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// DeleteQualifierOKCode is the HTTP code returned for type DeleteQualifierOK
const DeleteQualifierOKCode int = 200

/*DeleteQualifierOK Success

swagger:response deleteQualifierOK
*/
type DeleteQualifierOK struct {
}

// NewDeleteQualifierOK creates DeleteQualifierOK with default headers values
func NewDeleteQualifierOK() *DeleteQualifierOK {

	return &DeleteQualifierOK{}
}

// WriteResponse to the client
func (o *DeleteQualifierOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeleteQualifierDefault Generic error

swagger:response deleteQualifierDefault
*/
type DeleteQualifierDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteQualifierDefault creates DeleteQualifierDefault with default headers values
func NewDeleteQualifierDefault(code int) *DeleteQualifierDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteQualifierDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete qualifier default response
func (o *DeleteQualifierDefault) WithStatusCode(code int) *DeleteQualifierDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete qualifier default response
func (o *DeleteQualifierDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete qualifier default response
func (o *DeleteQualifierDefault) WithPayload(payload *models.Error) *DeleteQualifierDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete qualifier default response
func (o *DeleteQualifierDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteQualifierDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
