// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// GetReleaseQualifierOKCode is the HTTP code returned for type GetReleaseQualifierOK
const GetReleaseQualifierOKCode int = 200

/*GetReleaseQualifierOK Success

swagger:response getReleaseQualifierOK
*/
type GetReleaseQualifierOK struct {
}

// NewGetReleaseQualifierOK creates GetReleaseQualifierOK with default headers values
func NewGetReleaseQualifierOK() *GetReleaseQualifierOK {

	return &GetReleaseQualifierOK{}
}

// WriteResponse to the client
func (o *GetReleaseQualifierOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*GetReleaseQualifierDefault Generic error

swagger:response getReleaseQualifierDefault
*/
type GetReleaseQualifierDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReleaseQualifierDefault creates GetReleaseQualifierDefault with default headers values
func NewGetReleaseQualifierDefault(code int) *GetReleaseQualifierDefault {
	if code <= 0 {
		code = 500
	}

	return &GetReleaseQualifierDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get release qualifier default response
func (o *GetReleaseQualifierDefault) WithStatusCode(code int) *GetReleaseQualifierDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get release qualifier default response
func (o *GetReleaseQualifierDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get release qualifier default response
func (o *GetReleaseQualifierDefault) WithPayload(payload *models.Error) *GetReleaseQualifierDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get release qualifier default response
func (o *GetReleaseQualifierDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReleaseQualifierDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
