// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListReceptionHandlerFunc turns a function with the right signature into a list reception handler
type ListReceptionHandlerFunc func(ListReceptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListReceptionHandlerFunc) Handle(params ListReceptionParams) middleware.Responder {
	return fn(params)
}

// ListReceptionHandler interface for that can handle valid list reception params
type ListReceptionHandler interface {
	Handle(ListReceptionParams) middleware.Responder
}

// NewListReception creates a new http.Handler for the list reception operation
func NewListReception(ctx *middleware.Context, handler ListReceptionHandler) *ListReception {
	return &ListReception{Context: ctx, Handler: handler}
}

/*ListReception swagger:route GET /v{eventId}/list-reception admin listReception

ListReception list reception API

*/
type ListReception struct {
	Context *middleware.Context
	Handler ListReceptionHandler
}

func (o *ListReception) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListReceptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
