// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// ListReceptionOKCode is the HTTP code returned for type ListReceptionOK
const ListReceptionOKCode int = 200

/*ListReceptionOK Success

swagger:response listReceptionOK
*/
type ListReceptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListReceptionResponse `json:"body,omitempty"`
}

// NewListReceptionOK creates ListReceptionOK with default headers values
func NewListReceptionOK() *ListReceptionOK {

	return &ListReceptionOK{}
}

// WithPayload adds the payload to the list reception o k response
func (o *ListReceptionOK) WithPayload(payload *models.ListReceptionResponse) *ListReceptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list reception o k response
func (o *ListReceptionOK) SetPayload(payload *models.ListReceptionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListReceptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListReceptionDefault Generic error

swagger:response listReceptionDefault
*/
type ListReceptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListReceptionDefault creates ListReceptionDefault with default headers values
func NewListReceptionDefault(code int) *ListReceptionDefault {
	if code <= 0 {
		code = 500
	}

	return &ListReceptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list reception default response
func (o *ListReceptionDefault) WithStatusCode(code int) *ListReceptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list reception default response
func (o *ListReceptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list reception default response
func (o *ListReceptionDefault) WithPayload(payload *models.Error) *ListReceptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list reception default response
func (o *ListReceptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListReceptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
