// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateReceptionHandlerFunc turns a function with the right signature into a update reception handler
type UpdateReceptionHandlerFunc func(UpdateReceptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateReceptionHandlerFunc) Handle(params UpdateReceptionParams) middleware.Responder {
	return fn(params)
}

// UpdateReceptionHandler interface for that can handle valid update reception params
type UpdateReceptionHandler interface {
	Handle(UpdateReceptionParams) middleware.Responder
}

// NewUpdateReception creates a new http.Handler for the update reception operation
func NewUpdateReception(ctx *middleware.Context, handler UpdateReceptionHandler) *UpdateReception {
	return &UpdateReception{Context: ctx, Handler: handler}
}

/*UpdateReception swagger:route POST /v{eventId}/update-reception admin updateReception

UpdateReception update reception API

*/
type UpdateReception struct {
	Context *middleware.Context
	Handler UpdateReceptionHandler
}

func (o *UpdateReception) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateReceptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
