// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// UpdateReleaseQualifierOKCode is the HTTP code returned for type UpdateReleaseQualifierOK
const UpdateReleaseQualifierOKCode int = 200

/*UpdateReleaseQualifierOK Success

swagger:response updateReleaseQualifierOK
*/
type UpdateReleaseQualifierOK struct {
}

// NewUpdateReleaseQualifierOK creates UpdateReleaseQualifierOK with default headers values
func NewUpdateReleaseQualifierOK() *UpdateReleaseQualifierOK {

	return &UpdateReleaseQualifierOK{}
}

// WriteResponse to the client
func (o *UpdateReleaseQualifierOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateReleaseQualifierDefault Generic error

swagger:response updateReleaseQualifierDefault
*/
type UpdateReleaseQualifierDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateReleaseQualifierDefault creates UpdateReleaseQualifierDefault with default headers values
func NewUpdateReleaseQualifierDefault(code int) *UpdateReleaseQualifierDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateReleaseQualifierDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update release qualifier default response
func (o *UpdateReleaseQualifierDefault) WithStatusCode(code int) *UpdateReleaseQualifierDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update release qualifier default response
func (o *UpdateReleaseQualifierDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update release qualifier default response
func (o *UpdateReleaseQualifierDefault) WithPayload(payload *models.Error) *UpdateReleaseQualifierDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update release qualifier default response
func (o *UpdateReleaseQualifierDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReleaseQualifierDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
