// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// UpdateMatchOKCode is the HTTP code returned for type UpdateMatchOK
const UpdateMatchOKCode int = 200

/*UpdateMatchOK Success

swagger:response updateMatchOK
*/
type UpdateMatchOK struct {
}

// NewUpdateMatchOK creates UpdateMatchOK with default headers values
func NewUpdateMatchOK() *UpdateMatchOK {

	return &UpdateMatchOK{}
}

// WriteResponse to the client
func (o *UpdateMatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*UpdateMatchDefault Generic error

swagger:response updateMatchDefault
*/
type UpdateMatchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateMatchDefault creates UpdateMatchDefault with default headers values
func NewUpdateMatchDefault(code int) *UpdateMatchDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateMatchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update match default response
func (o *UpdateMatchDefault) WithStatusCode(code int) *UpdateMatchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update match default response
func (o *UpdateMatchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update match default response
func (o *UpdateMatchDefault) WithPayload(payload *models.Error) *UpdateMatchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update match default response
func (o *UpdateMatchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateMatchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
