// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/splathon/splathon-server/swagger/models"
)

// WriteNoticeOKCode is the HTTP code returned for type WriteNoticeOK
const WriteNoticeOKCode int = 200

/*WriteNoticeOK Success

swagger:response writeNoticeOK
*/
type WriteNoticeOK struct {
}

// NewWriteNoticeOK creates WriteNoticeOK with default headers values
func NewWriteNoticeOK() *WriteNoticeOK {

	return &WriteNoticeOK{}
}

// WriteResponse to the client
func (o *WriteNoticeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*WriteNoticeDefault Generic error

swagger:response writeNoticeDefault
*/
type WriteNoticeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWriteNoticeDefault creates WriteNoticeDefault with default headers values
func NewWriteNoticeDefault(code int) *WriteNoticeDefault {
	if code <= 0 {
		code = 500
	}

	return &WriteNoticeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the write notice default response
func (o *WriteNoticeDefault) WithStatusCode(code int) *WriteNoticeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the write notice default response
func (o *WriteNoticeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the write notice default response
func (o *WriteNoticeDefault) WithPayload(payload *models.Error) *WriteNoticeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the write notice default response
func (o *WriteNoticeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WriteNoticeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
